server:
  servlet:
    context-path: /shiro-springoot2
  port: 8082
spring:
  application:
    name: shiro-springboot
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 20
      max-wait-millis: 30000
  redis:
    host: 10.5.6.3
    port: 10200
    timeout: 5000ms
    database: 11
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 100ms
        min-idle: 10
mybatis:
  type-aliases-package:  com.yangzai.collection.entity
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-cfg.xml